version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: starci-inventory-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: inventory_user
      MONGO_INITDB_ROOT_PASSWORD: inventory_password
    ports:
      - "27017:27017"
    restart: always

# Run command:
# docker compose -f .docker/mongodb.yaml up --build -d
